name: basesource
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  webview_flutter: ^3.0.1
  dio_http_cache: ^0.3.0
  velocity_x: ^3.4.0
  camera: ^0.9.4+16
  image_picker: ^0.8.4+11
  flutter_toggle_tab: ^1.1.7
  video_player: ^2.3.0

  flutter: 
    sdk: flutter
  intl: ^0.17.0
  dio: ^4.0.4

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

